title: sdsdsd
description: wefewfwf
social_link: djfw_
social_username: djfw_
github_repo: 1xn
github_username: 1xn
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /calamitous_locomotive
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
